Ability to use saved display filters
orgcandman/pcap-mode pull request #7
Opened 2016-10-08 05:20 UTC by vapniks

2016-10-08 05:21 UTC, vapniks commented
Added command for reading ~/wireshark/dfilters file and prompting for a named display filter.
Also quick convenience function for clearing the current filter.

2016-10-10 13:37 UTC, apconole requested changes
Thanks for this.  I think after a round of fixups this will be acceptable.

Please also make sure to add a signed-off-by line, to acknowledge that your contribution is covered under the GNU GPL (git commit -s), and update the changelog in the pcap-mode.el file.

2016-10-10 13:37 UTC, orgcandman commented on pcap-mode.el
> -                                        (message "tshark filter \"%s\""
Why these whitespace changes?  Please drop them.

2016-10-10 13:37 UTC, orgcandman commented on pcap-mode.el
> +(defun pcap-mode-set-named-filter (filter-name)
Please update the documentation string to include the purpose of FILTER-NAME

2016-10-10 13:37 UTC, orgcandman commented on pcap-mode.el
> +  (interactive (list (ido-completing-read
This requires ido mode, but there's no hint that such a change is required.  Please use completing-read.  You may also choose to write a function which detects the presence of ido-mode and prefers it vs. completing-read, with a fallback to completing-read.  Example below is completly untested:

(defun pcap-mode--completing-read ()
 "Returns the preferred completing read function."
  (if (fboundp ido-completing-read) ido-completing-read
    completing-read))

2016-10-10 13:37 UTC, orgcandman commented on pcap-mode.el
> +(defun pcap-mode-clear-filter nil
Can you split this series into three commits.  Commit one can fix the group binding for the custom variables above, commit two can add the clear-filter, commit three can add the new scanning code.

ALSO, this function has no documentation.

2016-10-10 13:37 UTC, orgcandman commented on pcap-mode.el
> +  (let (filter)
This code looks eerily similar to the interactive completion code.  Can you abstract this out into something like pcap-mode--dfilters-selection or something?

2016-10-10 13:37 UTC, orgcandman commented on pcap-mode.el
> +    (define-key kmap (kbd "g") 'pcap-mode-clear-filter)
I'm happy to see additional functions added to the default keymap.  Please update the README as well.

2016-10-10 13:37 UTC, orgcandman commented on pcap-mode.el
> +  :type 'string
Please put this change, and the similar one below (for pcap-mode-tshark-single-packet-filter) in a separate commit.

2016-10-11 12:25 UTC, vapniks commented on pcap-mode.el
> +  :type 'string
done

2016-10-11 12:41 UTC, vapniks commented on pcap-mode.el
> +  :type 'string
Have updated the changelog, but forgot to add signed off lines, sorry (aren't my changes automatically covered by the GPL anyway?).

2016-10-11 12:42 UTC, vapniks commented on pcap-mode.el
> +    (define-key kmap (kbd "g") 'pcap-mode-clear-filter)
done

2016-10-11 12:43 UTC, vapniks commented on pcap-mode.el
> -                                        (message "tshark filter \"%s\""
This is an artifact of `aggressive-indent` mode, some of your whitespace was non-standard (opening parentheses should always be to the right of opening parentheses of parent sexp's).

2016-10-11 12:44 UTC, vapniks commented on pcap-mode.el
> +(defun pcap-mode-set-named-filter (filter-name)
done

2016-10-11 12:44 UTC, vapniks commented on pcap-mode.el
> +  (interactive (list (ido-completing-read
done (differently)

2016-10-11 12:44 UTC, vapniks commented on pcap-mode.el
> +  (let (filter)
done, (but not sure it was worth it).

2016-10-11 12:45 UTC, vapniks commented on pcap-mode.el
> +(defun pcap-mode-clear-filter nil
done

2016-10-11 13:40 UTC, orgcandman commented
Thanks for your contribution!  I manually cherry picked them to avoid the big 'add then revert' commit in the middle.

2016-10-11 13:40 UTC, closed without merging